In [9]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [10]:
#############
### Problem 1

In [11]:
# nSet = pd.Series(np.array([1,2,3,5,10,30]))
# thetaSet = pd.Series(np.array([1,5,50,100]))
nSet = np.array([1,2,3,5,10,30])
thetaSet = np.array([1,5,50,100])

In [12]:
ntSet = np.zeros((nSet.size*thetaSet.size,2), dtype='int8')
index: int = 0
for n in nSet:
    for theta in thetaSet:
        ntSet[index] = [n, theta]
        index += 1

In [25]:
def Q1_solver(N, ntSet, rtype='print'):
    # create sample sets
    if rtype == 'table':
        table_mle = np.zeros((nSet.size,thetaSet.size), dtype='float')
        table_moment = np.zeros((nSet.size,thetaSet.size), dtype='float')
        
    for nt in ntSet:
        # replicate for N times
        n = nt[0]
        theta = nt[1]
        mleSet = np.zeros(N+1, dtype='float')
        momentSet = np.zeros(N+1, dtype='float')
        mse_mleCum = 0
        mse_momentCum = 0
        # Monte Carlo simulation
        for i in range(N):
            data = np.random.uniform(0,theta,n)
            # mleSet build
            mleSet[n] = np.max(data)
            mse_mleCum += np.square(mleSet[n] - theta)/N
            # momentSet build
            momentSet[n] = 2*np.mean(data)
            mse_momentCum += np.square(momentSet[n] - theta)/N
        # Monte_carlo finish
        if rtype == 'print':
            print('n: ',n, 'theta: ',theta)
            print('MSE of MLE Estimator: ',mse_mleCum)
            print('MSE of Moment Estimator ', mse_momentCum)
            print()
        elif rtype == 'table':
            from tabulate import tabulate
            table_mle[np.where(nSet==1), np.where(thetaSet==1)] = mse_mleCum
            table_moment[np.where(nSet==1), np.where(thetaSet==1)] = mse_momentCum
                
            
            

In [26]:
# Q1.b: n=1, theta=1
Q1_solver(1000,np.array([[1,1]]))

n:  1 theta:  1
MSE of MLE Estimator:  0.33394761859671485
MSE of Moment Estimator  0.335045892442637



In [56]:
table = np.zeros((6,4),dtype='int8')
table

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int8)

In [61]:
table[1,1] = 1
print(table)
i,j = np.where(table==1)
print(i,j)

[[0 0 0 0]
 [0 1 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[1] [1]


In [70]:
i = np.where(nSet==1)
j = np.where(thetaSet==1)
table[i,j]

array([[0]], dtype=int8)

In [ ]:
#############
### Problem 2